# Generated by Django 2.2.6 on 2019-10-31 05:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('last_change', models.DateTimeField(auto_now=True, verbose_name='Last change')),
                ('image_file', models.ImageField(blank=True, max_length=500, null=True, upload_to='', verbose_name='Image')),
                ('title', models.CharField(blank=True, max_length=350, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('last_change', models.DateTimeField(auto_now=True, verbose_name='Last change')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('last_change', models.DateTimeField(auto_now=True, verbose_name='Last change')),
                ('title', models.CharField(max_length=511, verbose_name='Title')),
                ('label', models.CharField(blank=True, default='', max_length=255, verbose_name='Label')),
                ('lead_text', models.TextField(blank=True, default='', verbose_name='Lead text')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
                ('publish_from', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Publish from')),
                ('publish_to', models.DateTimeField(blank=True, null=True, verbose_name='Publish to')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is published')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('alter_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alter_image', to='content.Image')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='content.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
