# Generated by Django 2.2.6 on 2019-11-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20191104_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(to='content.Keyword', verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(max_length=500, upload_to='upload', verbose_name='Image'),
        ),
    ]
